--15--
SELECT name, id_group FROM t_material;
--16--
SELECT name, surname, father_name, birthdate FROM t_employer;
--17--
SELECT name FROM t_employer WHERE sex LIKE 'M';
--18--
SELECT * FROM t_caterer WHERE id_caterer IN 
  (SELECT id_ceterer FROM t_supply 
    WHERE supply_date BETWEEN '1.04.2009' AND '30.06.2009');
--19--
SELECT * FROM t_section WHERE id_section NOT IN
  (SELECT id_section FROM t_deliver
    WHERE deliver_date LIKE '%07.2009');
--20--
SELECT name FROM t_section WHERE id_section IN 
  (SELECT id_section FROM t_deliver
     WHERE deliver_date = SYSDATE);
--21--
SELECT name FROM t_material WHERE id_material IN 
  (SELECT id_material FROM t_supply
    WHERE supply_date LIKE '%2017');
--22--
SELECT name FROM t_material WHERE id_material NOT IN
  (SELECT id_material FROM t_supply 
    WHERE supply_date LIKE '%2017')
  AND id_material IN
    (SELECT id_material FROM t_supply
      WHERE VOLUME LIKE 0);
--23--
SELECT T_SECTION.NAME,T_SECTION.ID_SECTION,
  T_EMPLOYER.NAME,T_EMPLOYER.SURNAME,T_EMPLOYER.FATHER_NAME
  FROM T_SECTION,T_EMPLOYER
  WHERE T_SECTION.ID_EMPLOYER = T_EMPLOYER.ID_EMPLOYER;
--24--
SELECT T_SECTION.NAME,T_EMPLOYER.NAME,T_EMPLOYER.SURNAME,
  T_EMPLOYER.FATHER_NAME,T_JOB.NAME
  FROM T_SECTION,T_EMPLOYER,T_JOB
  WHERE T_SECTION.ID_EMPLOYER = T_EMPLOYER.ID_EMPLOYER
  AND T_EMPLOYER.ID_JOB = T_JOB.ID_JOB;
--25--
SELECT T_CATERER.NAME,T_MATERIAL.NAME, T_SUPPLY.VOLUME,
  T_INPRICE.PRICE,T_SUPPLY.SUPPLY_DATE
  FROM T_CATERER,T_MATERIAL, T_SUPPLY, T_INPRICE
  WHERE T_CATERER.ID_CATERER IN 
  (SELECT ID_CATERER FROM T_SUPPLY 
    WHERE SUPPLY_DATE BETWEEN '1.01.2009' AND '31.03.2009')
  AND T_MATERIAL.ID_MATERIAL = T_INPRICE.ID_MATERIAL
  AND T_MATERIAL.ID_MATERIAL = T_SUPPLY.ID_MATERIAL
  AND T_CATERER.ID_CATERER = T_SUPPLY.ID_CATERER;
--26--
SELECT T_CATERER.NAME,T_MATERIAL.NAME, T_SUPPLY.VOLUME,
  T_INPRICE.PRICE,T_SUPPLY.SUPPLY_DATE
  FROM T_CATERER,T_MATERIAL, T_SUPPLY, T_INPRICE
  WHERE T_CATERER.ID_CATERER IN 
  (SELECT ID_CATERER FROM T_SUPPLY 
    WHERE SUPPLY_DATE BETWEEN '1.01.2009' AND '31.03.2009')
  AND T_MATERIAL.ID_MATERIAL = T_INPRICE.ID_MATERIAL
  AND T_MATERIAL.ID_MATERIAL = T_SUPPLY.ID_MATERIAL
  AND T_CATERER.ID_CATERER = T_SUPPLY.ID_CATERER
  AND T_CATERER.LEGAL_ADDRESS LIKE 'Пермь%';
--27--
SELECT T_MATERIAL.ID_MATERIAL, T_MATERIAL_NAME,
  T_STORE_NAME,T_SURPLUS.VOLUME
  FROM T_MATERIAL, T_STORE, T_SURPLUS
  WHERE T_STORE.ID_STORE = T_SURPLUS.ID_STORE
  AND T_MATERIAL.IDMATERIAL = T_SURPLUS.ID_ID_MATERIAL
  ORDER BY T_MATERIAL.ID_MATERIAL;
--28--
SELECT T_CATERER.NAME, T_MATERIAL.NAME, T_SUPPLY.VOLUME,
  T_INPRICE.PRICE, T_SUPPLY.DATE
  FROM T_CATERER.ID_CATERER IN 
  (SELECT ID_CATERER FROM T_SUPPLY
    WHERE SUPPLY_DATE BETWEEN '1.01.2009' AND '31.03.2009')
    JOIN T_SUPPLY 
      ON T_SUPPLY.ID_MATERIAL = T_MATERAIL.ID_MATERIAL
    AND T_SUPPLY.ID_CATERER = T_CATERER.ID_CATERER
    JOIN T_INPRICE
      ON T_INPRICE.ID_MATERIAL =T_MATERIAL.ID_MATERAIL;
--29--
SELECT T_CATERER.NAME, T_MATERIAL.NAME, T_SUPPLY.VOLUME, 
       T_INPRICE.PRICE, T_SUPPLY.SUPPLY_DATE
  FROM T_CATERER LEFT JOIN T_SUPPLY 
    ON T_SUPPLY.ID_CATERER = T_CATERER.ID_CATERER
  LEFT JOIN T_MATERIAL
    ON T_SUPPLY.ID_MATERIAL = T_MATERIAL.ID_MATERIAL
  LEFT JOIN T_INPRICE
    ON T_INPRICE.ID_MATERIAL = T_MATERIAL.ID_MATERIAL;
--30--
SELECT T_STORE.ID_STORE, T_STORE.NAME,
       T_MATERIAL.NAME, T_SURPLUS.VOLUME
  FROM T_STORE LEFT JOIN T_SURPLUS
    ON T_STORE.ID_STORE = T_SURPLUS.ID_STORE
  LEFT JOIN T_MATERIAL 
    ON T_MATERIAL.ID_MATERIAL = T_SURPLUS.ID_MATERIAL
  ORDER BY T_STORE.ID_STORE;
--31--
SELECT T_MATERIAL.ID_MATERIAL, T_MATERIAL.NAME,
       T_MESSURE.NAME, T_INPRICE.PRICE
  FROM T_MATERIAL JOIN T_MESSURE 
    ON T_MATERIAL.ID_MESSURE = T_MESSURE.ID_MESSURE
  JOIN T_INPRICE 
    ON T_INPRICE.ID_MATERIAL = T_MATERIAL.ID_MATERIAL
      AND T_INPRICE.PRICE_DATE IN
        (SELECT PRICE_DATE FROM T_INPRICE 
           WHERE PRICE_DATE BETWEEN '01.07.2009' AND '30.09.2009');
--32--
SELECT T_MATERIAL.ID_MATERIAL, T_MATERIAL.NAME,
       T_MESSURE.NAME, T_INPRICE.PRICE
  FROM T_MATERIAL LEFT JOIN T_MESSURE 
    ON T_MATERIAL.ID_MESSURE = T_MESSURE.ID_MESSURE
  LEFT JOIN T_INPRICE 
    ON T_INPRICE.ID_MATERIAL = T_MATERIAL.ID_MATERIAL;
--33--
ALTER TABLE T_EMPLOYER
  ADD ID_MANAGER INT;
UPDATE T_EMPLOYER
  SET ID_MANAGER = 1
    WHERE ID_EMPLOYER BETWEEN 1 AND 3;
UPDATE T_EMPLOYER
  SET ID_MANAGER = 2
    WHERE ID_EMPLOYER LIKE 4;
--34--
ALTER TABLE T_GROUP
  ADD MINI_GROUP INT;
UPDATE T_GROUP
  SET MINI_GROUP = 1
    WHERE ID_GROUP BETWEEN 1 AND 3;
UPDATE T_GROUP
  SET MINI_GROUP = 2
    WHERE ID_GROUP > 3;
SELECT * FROM T_GROUP 
  WHERE MINI_GROUP = 1;
SELECT * FROM T_GROUP 
  WHERE MINI_GROUP = 2;
--35--
CREATE TABLE t_exemp(
  id_employer INT NOT NULL,
  Name NVARCHAR2(150) NOT NULL,
  Surname NVARCHAR2(150) NOT NULL,
  Father_Name NVARCHAR2(150),
  Bithdate DATE,
  ID_JOB INT,
  ID_MANAGER INT,
  CONSTRAINT pk_exemp
    PRIMARY KEY (ID_EMPLOYER));
INSERT INTO T_EXEMP (ID_EMPLOYER, NAME, SURNAME, FATHER_NAME, 
    BITHDATE, ID_JOB, ID_MANAGER)
  VALUES (1, 'Name', 'Surname', 'Father_name', '1.01.01', 2, 1);
--36--
ALTER TABLE T_EXEMP
  ADD DISMISSED DATE;
UPDATE T_EXEMP
  SET DISMISSED = '2.02.02';
--37--
CREATE TABLE t_contact(
  ID_Contact INT NOT NULL,
  ID_Caterer INT,
  Name NVARCHAR2(150) NOT NULL,
  Surname NVARCHAR2(150) NOT NULL,
  Father_Name NVARCHAR2(150),
  Telephon NVARCHAR2(150) NOT NULL,
  CONSTRAINT PK_contact
    PRIMARY KEY (ID_CONTACT),
  CONSTRAINT FK_contact_caterer
    FOREIGN KEY (ID_CATERER) REFERENCES T_CATERER(ID_CATERER) 
      ON DELETE CASCADE);
INSERT INTO T_CONTACT (ID_CONTACT, ID_CATERER, NAME, SURNAME, FATHER_NAME, TELEPHON)
  VALUES (1, 1, '1', '1', '1', '111');
INSERT INTO T_CONTACT (ID_CONTACT, ID_CATERER, NAME, SURNAME, FATHER_NAME, TELEPHON)
  VALUES (2, 2, '2', '2', '2', '222');
INSERT INTO T_CONTACT (ID_CONTACT, ID_CATERER, NAME, SURNAME, FATHER_NAME, TELEPHON)
  VALUES (3, 3, '3', '3', '3', '333');
INSERT INTO T_CONTACT (ID_CONTACT, ID_CATERER, NAME, SURNAME, FATHER_NAME, TELEPHON)
  VALUES (4, 3, '4', '4', '4', '444');
INSERT INTO T_CONTACT (ID_CONTACT, ID_CATERER, NAME, SURNAME, FATHER_NAME, TELEPHON)
  VALUES (5, 5, '5', '5', '5', '555');
SELECT NAME, SURNAME, FATHER_NAME, TELEPHON FROM T_CONTACT;
--38--
SELECT * FROM T_CATERER
  ORDER BY NAME;
--39--
SELECT * FROM T_CATERER JOIN T_CONTACT
    ON T_CATERER.ID_CATERER = T_CONTACT.ID_CATERER
  ORDER BY T_CATERER.NAME, T_CONTACT.SURNAME, T_CONTACT.NAME, FATHER_NAME;
--40--
SELECT T_STORE.NAME, T_MATERIAL.NAME, T_SURPLUS.VOLUME
  FROM T_STORE LEFT JOIN T_SURPLUS 
    ON T_STORE.ID_STORE = T_SURPLUS.ID_STORE
  LEFT JOIN T_MATERIAL 
    ON T_MATERIAL.ID_MATERIAL = T_SURPLUS.ID_MATERIAL
  ORDER BY T_STORE.ID_STORE, T_SURPLUS.VOLUME DESC; 
--41--
SELECT T_MATERIAL.NAME AS "material", T_CATERER.NAME AS "caterer", SUM(T_SUPPLY.VOLUME) AS "volume"
  FROM T_CATERER JOIN T_SUPPLY 
    ON T_CATERER.ID_CATERER = T_SUPPLY.ID_CATERER
  JOIN T_MATERIAL
    ON T_MATERIAL.ID_MATERIAL = T_SUPPLY.ID_MATERIAL
  WHERE T_SUPPLY.SUPPLY_DATE BETWEEN '1.01.2017'
     AND T_SUPPLY.SUPPLY_DATE '31.12.2017'
  GROUP BY T_MATERIAL.NAME, T_CATERER.NAME
  ORDER BY T_CATERER.NAME, T_MATERIAL.NAME;
--45--
SELECT NAME FROM T_STORE INNER JOIN T_SURPLUS
  ON T_STORE.ID_STORE = T_SURPLUS.ID_STORE
  GROUP BY NAME HAVING SUM(VOLUME) = 0;
--46--
SELECT NAME FROM T_CATERER INNER JOIN T_SUPPLY
  ON T_CATERER.ID_CATERER = T_SUPPLY.ID_CATERER
  WHERE SUPPLY_DATE >= '1.01.2017' 
    AND T_SUPPLY.SUPPLY_DATE <= '31.12.2017'
  GROUP BY NAME HAVING SUM(VOLUME) < 1000;
--47--
SELECT NAME FROM T_CATERER JOIN T_SUPPLY
  ON T_CATERER.ID_CATERER = T_SUPPLY.ID_CATERER
  WHERE SUPPLY_DATE >= '1.01.2017' 
    AND T_SUPPLY.SUPPLY_DATE <= '31.12.2017'
  GROUP BY NAME HAVING SUM(VOLUME) = MAX(VOLUME);
  GROUP BY NAME HAVING SUM(VOLUME) = MAX(VOLUME);