--48--
CREATE VIEW NUMB48 
  (T_CATERER.NAME, T_CONTACT.NAME, T_CONTACT.SURNAME)
AS
  SELECT T_CATERER.NAME, T_CONTACT.NAME, T_CONTACT.SURNAME
    FROM T_CATERER JOIN T_CONTACT
    ON T_CATERER.ID_CATERER = T_CONTACT.ID_CATERER;


SELECT * FROM NUMB48;


INSERT INTO NUMB48
  (T_CATERER.NAME, T_CONTACT.NAME, T_CONTACT.SURNAME)
  VALUES
  ('Поставщик', 'Имя', 'Фамилия');


DELETE FROM NUMB48
  WHERE ID_CATERER = 2;


UPDATE NUMB48
  SET T_CONTACT.NAME = 'HE-MAN'
    WHERE ID_CATERER = 2;

--49--
CREATE VIEW NUMB49
  (MATERIAL, STORE, VOLUME)
AS
  SELECT T_MATERIAL.NAME, T_STORE.NAME, SUM(T_SURPLUS.VOLUME)
    FROM T_MATERIAL JOIN T_SURPLUS  
      ON T_MATERIAL.ID_MATERIAL = T_SURPLUS.ID_MATERIAL
    JOIN T_STORE 
      ON T_SURPLUS.ID_STORE = T_STORE.ID_STORE
    GROUP BY T_MATERIAL.NAME, T_STORE.NAME;

--50--
CREATE VIEW NUMB50
  (T_CATERER.NAME, MATERIAL, MESSURE, SUPPLY_DATE, PRICE, VOLUME, SUMM)
AS
  SELECT T_CATERER.NAME, T_MATERIAL.NAME, T_MESSURE.NAME, 
         T_SUPPLY.SUPPLY_DATE, T_INPRICE.PRICE,
         T_SUPPLY.VOLUME, T_SUPPLY.VOLUME * T_INPRICE.PRICE
  FROM T_SUPPLY JOIN T_CATERER 
    ON T_SUPPLY.ID_CATERER = T_CATERER.ID_CATERER
  JOIN T_MATERIAL 
    ON T_SUPPLY.ID_MATERIAL = T_MATERIAL.ID_MATERIAL
  JOIN T_MESSURE 
    ON T_MATERIAL.ID_MESSURE = T_MESSURE.ID_MESSURE
  JOIN T_INPRICE 
    ON T_MATERIAL.ID_MATERIAL = T_INPRICE.ID_MATERIAL;

  --51--
CREATE VIEW NUMB51
  (T_CATERER.NAME, MATERIAL, MESSURE, SUPPLY_DATE, PRICE, VOLUME, SUMM)
AS
  SELECT T_CATERER.NAME, T_MATERIAL.NAME, T_MESSURE.NAME, 
         T_SUPPLY.SUPPLY_DATE, T_INPRICE.PRICE,
         T_SUPPLY.VOLUME, T_SUPPLY.VOLUME * T_INPRICE.PRICE
  FROM T_SUPPLY JOIN T_CATERER 
    ON T_SUPPLY.ID_CATERER = T_CATERER.ID_CATERER
  JOIN T_MATERIAL 
    ON T_SUPPLY.ID_MATERIAL = T_MATERIAL.ID_MATERIAL
  JOIN T_MESSURE 
    ON T_MATERIAL.ID_MESSURE = T_MESSURE.ID_MESSURE
  JOIN T_INPRICE 
    ON T_MATERIAL.ID_MATERIAL = T_INPRICE.ID_MATERIAL;

--52--
CREATE VIEW NUMB52
  (ID, MATERIAL, VOLUME, STORE, PRICE, SUMM)
AS
  SELECT T_SUPPLY.ID_SUPPLY, T_MATERIAL.NAME, T_SUPPLY.VOLUME, 
         T_STORE.NAME, T_SUPPLY.PRICE, 
         T_SUPPLY.VOLUME * T_SUPPLY.PRICE
  FROM T_SUPPLY JOIN T_MATERIAL 
    ON T_SUPPLY.ID_MATERIAL = T_MATERIAL.ID_MATERIAL
  JOIN T_STORE 
    ON T_SUPPLY.ID_STORE = T_STORE.ID_STORE
  ORDER BY T_SUPPLY.ID_SUPPLY;


CREATE VIEW NUMB52_1
  (ID, MATERIAL, VOLUME, STORE, PRICE, SUMM)
AS
  SELECT T_SUPPLY.ID_SUPPLY, T_MATERIAL.NAME, T_SUPPLY.VOLUME, 
         T_STORE.NAME, T_INPRICE.PRICE, 
         T_SUPPLY.VOLUME * T_INPRICE.PRICE
  FROM T_SUPPLY JOIN T_MATERIAL 
    ON T_SUPPLY.ID_MATERIAL = T_MATERIAL.ID_MATERIAL
  JOIN T_INPRICE 
    ON T_MATERIAL.ID_MATERIAL = T_INPRICE.ID_MATERIAL
  JOIN T_STORE 
    ON T_SUPPLY.ID_STORE = T_STORE.ID_STORE
  ORDER BY T_SUPPLY.ID_SUPPLY;


CREATE VIEW COMPARE
  (MATERIAL, VOLUME, STORE, SUPPLY_PRICE, INPRICE)
AS
  SELECT T_MATERIAL.NAME, T_SUPPLY.VOLUME, T_STORE.NAME,
         SUPPLY_PRICE.SUMM, INPRICE.SUMM, 
         ABS(SUPPLY_PRICE.SUMM - INPRICE.SUMM)
  FROM T_SUPPLY JOIN T_MATERIAL 
    ON T_SUPPLY.ID_MATERIAL = T_MATERIAL.ID_MATERIAL
  JOIN T_STORE 
    ON T_SUPPLY.ID_STORE = T_STORE.ID_STORE
  JOIN SUPPLY_PRICE 
    ON T_SUPPLY.ID_SUPPLY = SUPPLY_PRICE.ID
  JOIN INPRICE 
    ON T_SUPPLY.ID_SUPPLY = INPRICE.ID; 