CREATE SEQUENCE seq_caterer
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE seq_deliver
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE seq_employer
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE seq_group
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE seq_inprice
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE seq_surplus
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE seq_material
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE seq_messure
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE seq_section
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE seq_store
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE seq_supply
  START WITH 1
  INCREMENT BY 1;

